name: Skilled_worker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  smooth_page_indicator:
  get:
  carousel_slider:
  hexcolor:
  flutter_svg:
  wave:
  lottie:
  fluttertoast: ^8.0.8
  image_picker: ^1.0.7
  country_state_city: ^0.1.6
  curved_navigation_bar: ^1.0.3
  shared_preferences:
  google_nav_bar: ^5.0.6
  permission_handler: ^11.3.1
  firebase_auth: ^4.17.7
  firebase_core:
  firebase_storage: ^11.6.9
  geolocator: ^7.6.2
  geocoding: ^3.0.0
  animated_notch_bottom_bar: ^1.0.1
  cloud_firestore: ^4.15.8
  animated_splash_screen: ^1.3.0
  liquid_swipe: ^3.1.0
  firebase_messaging: ^14.7.20
  firebase_database:
  connectivity: ^3.0.6
  shimmer:
  flutter_content_placeholder: ^0.0.1
  dropdown_button2: ^2.3.9
  razorpay_flutter: ^1.3.6
  flutter_local_notifications: ^13.0.0
  intl: ^0.19.0
  rxdart: ^0.27.7
  timezone: ^0.9.2
  flutter_file_dialog: ^3.0.2
#  gallery_saver_plus: ^3.0.1
  http: ^0.13.6
  connectivity_plus: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding/

  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript.ttf

    - family: Oswald
      fonts:
        - asset: fonts/Oswald.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins.ttf